apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: t0ftoivul-nodejs 
  janus-idp.io/tekton: t0ftoivul-nodejs
  backstage.io/kubernetes-id: t0ftoivul-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t0ftoivul-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  